from binary_search import binary_search
from insertion_sort import InsertionSort
from LinkedList import DoubleLinkedList
from LinkedList import SingleLinkedList
from selection_sort import SelectionSort